name: build & push images weekly
on:
  workflow_dispatch:
  push:
    branches: [master]
  schedule:
    - cron: 0 0 * * 0 # weekly

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: modules/
          file: modules/Dockerfile.alpine
          push: true
          build-args: |
            ENABLED_MODULES=brotli
          tags: |
            ghcr.io/rajveermalviya/nginx-brotli:mainline-alpine
